---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
---


# introduction

My name is Nankun Liu and here is my experience.

# 1. Education

## Columbia University, Mailman School of Public Health   

New York, NY 

MPH | Major in Biostatistics | Certificate in Advanced Epidemiology 

Graduation expected: May 2020

Current GPA 3.516/4.0 

## University of Missouri-Columbia  

Columbia, MO

Bachelor of Science | Major in Biology | Minor in Chemistry      

Graduated May 2018

Overall GPA 3.716/4.0; Dean’s List (2014-2017) 


# 2. Work Experience

## Beijing Center for Disease Prevention and Control

Beijing, China Information Analyst, Lab Technician (Internship)  May-Aug. 2018 • Conducted data analysis, retrieved and translated documents related to Listeria. Utilized Excel to analyze 27 complex samples. • Accurately followed protocols to gather samples of circulating food, treat samples for enzymatic hydrolysis, dispensing, preservation etc., in order to prevent outbreaks of Listeria. • Ensured samples were properly handled; managed colony treatment, bacterial inoculation, expanded culture, species identification, and utilized DNA analyzer. • Provided health counseling to elderly individuals; and responsible for health science manual selection. 

## Demeixinda Medical-Device Technology Co., Ltd.

Beijing, China Equipment Engineer Assistant (Internship)                                             May-June 2017 • Collected production status data from records below in order to make a summary report for analysis. • Monitored amount of required materials, inspected for defects and ensured compliance with manufacturing protocols, report suspected defaults and potential shortage. • Assembled and installed endoscope mainframe and light sources, HD and fiber ultrasonic electronic bronchoscope in hospitals. • Used attention to detail to inspect and test the final products; diagnosed and repaired problem products, report any procedures and results. 

