---
title: "Dashbroad"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

set.seed(1551)

data(rest_inspec)
ri_md = 
  rest_inspec %>% 
  select(boro, critical_flag, cuisine_description, inspection_date, score) %>% 
  filter(!is.na(score)) %>% 
  sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
Cri_fla =
  ri_md %>%
  drop_na() %>% 
  filter(critical_flag != "Not Applicable") %>% 
  mutate(area = boro) %>% 
  group_by(area, critical_flag) %>% 
  summarize(n = n()) %>% 
 plot_ly(x = ~area, y = ~n, color = ~critical_flag, type = "bar")
Cri_fla
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
sco_bor =
  ri_md %>%
  drop_na() %>% 
 ggplot(aes(x = boro, y = score, fill = boro)) +
  geom_boxplot() +
  labs(
    title = "restarant score across area",
    x = "Area",
    y = "Violation score"
  )+
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(sco_bor)
```

### Chart C

```{r}
 sca_cui =
ri_md %>%
  filter(cuisine_description == "Donuts"|cuisine_description == "Ice Cream, Gelato, Yogurt, Ices"|cuisine_description == "Juice, Smoothies, Fruit Salads"|cuisine_description == "Salads") %>% 
  drop_na() %>% 
  group_by(cuisine_description, boro) %>% 
  summarize(
    ave = mean(score) 
  ) %>% 
  ggplot(aes(x = boro, y = ave, color = cuisine_description))+
    geom_point()+
    labs(
    title = "average score across cuisines",
    x = "cuisine type",
    y = "Average violation score"
  )+
    theme_classic() + 
    theme(axis.text.x = element_text(angle = 15, hjust = 1))
ggplotly(sca_cui)
```

rmarkdown::render("Dashbroad.Rmd", output_format = "flexdashboard::flex_dashboard")

